spring.application.name=assignment1112.Main
server.port=8080
logging.config=src/main/resources/log4j2.xml


spring.datasource.url=jdbc:postgresql://localhost:5432/productdb
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true